 apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shady
  template:
    metadata:
      labels:
        app: shady
    spec:
      containers:
      - name: portfolio
        image: shady203/portfolio-template:IMAGE_TAG
        ports:
        - containerPort: 80

