apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: shady
spec:
  selector:
    app: shady
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30055
  type: NodePort
